#!/bin/sh -e

set -x

mypy starlette_admin --ignore-missing-imports
autoflake --in-place --recursive --remove-unused-variables starlette_admin tests
black starlette_admin tests
isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 88 --recursive --apply starlette_admin tests